version: '3.8'
services:
  nuxt3-app:
    image: guangjibin/nuxt3-app:latest  # 如docker.io/你的用户名/nuxt3-app:latest
    container_name: vigorbuysheet-docker
    restart: always  # 宝塔崩溃自动重启
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/_health"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge