version: '3.8'
services:
  nuxt-app:
    image: ${DOCKER_HUB_USERNAME}/nuxt-sheet:latest  # 替换为你的镜像地址
    container_name: nuxt-docker-app
    user: www:www  # 宝塔专属：www用户运行
    ports:
      - "3000:3000"  # 宝塔已放行的端口
    volumes:
      - /www/wwwroot/nuxt-sheet-docker:/app  # 挂载宝塔站点目录
    restart: always  # 异常自动重启
    networks:
      - baota-network  # 宝塔网络（可选）

networks:
  baota-network:
    driver: bridge